name = "ewdev/vide_nts_types"
version = "0.1.0"
description = "Vide type overrides for the new typesolver"
authors = ["EwDev (https://ewdev.net/)"]
repository = "https://github.com/ewd3v/vide_nts_types"
license = "MIT"
includes = ["src/**", "pesde.toml", "LICENSE", "README.md"]

[engines]
pesde = "^0.7.3"
lune = "^0.10.4"

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"
analyze = "scripts/analyze.luau"
build = "scripts/build.luau"
format_check = "scripts/format_check.luau"
test = "scripts/test.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.2.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.6.1", target = "lune" }
stylua = { name = "pesde/stylua", version = "^2.4.1", target = "lune" }
luau-lsp = { name = "pesde/luau_lsp", version = "^1.66.0", target = "lune" }
selene = { name = "pesde/selene", version = "^0.30.1", target = "lune" }

[dependencies]
vide = { name = "centau/vide", version = "^0.4.0" }
